### ISSUE TITLE
docker issue

### ISSUE THREAD

**Issue by Shadoukun** [TannerReynolds/ShareX-Custom-Upload-Server#1]
So, I'm attempting to run this in a docker container. It works as expected in a container, but if I attempt to mount 'uploads' to a host directory (i.e. `-v /path/to/host/uploads:/sharex/uploads`), I then get an error when I attempt to upload files

```
sharex-server_1  | TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type object
sharex-server_1  |     at write_ (_http_outgoing.js:601:11)
sharex-server_1  |     at ServerResponse.write (_http_outgoing.js:573:10)
sharex-server_1  |     at fs.rename.err (/sharex/app.js:301:32)
sharex-server_1  |     at FSReqWrap.oncomplete (fs.js:145:20)
```

Any ideas?

If it's helpful, my Dockerfile is

```dockerfile
from node:alpine

RUN apk add --no-cache git
RUN git clone https://github.com/TannerReynolds/node-sharex-server /sharex

WORKDIR /sharex

RUN npm install
RUN npm install -g pm2

VOLUME ["/sharex/pages", "/sharex/uploads"]

EXPOSE 80

cmd ["pm2-docker", "start", "app.js"]
```

**Edit:**

Okay. I figured it out. the *actual* error is:

```
{ [Error: EXDEV: cross-device link not permitted, rename '/tmp/upload_20130982b474a921caed4722c2fbba20' -> './uploads/MFA6Y9.png']
sharex-server_1  |   errno: -18,
sharex-server_1  |   code: 'EXDEV',
sharex-server_1  |   syscall: 'rename',
sharex-server_1  |   path: '/tmp/upload_20130982b474a921caed4722c2fbba20',
sharex-server_1  |   dest: './uploads/MFA6Y9.png' }
```

After some googling, I installed `fs-extra` and replaced all instances of `fs.rename` with `fs.move`, which seems to have fixed the problem with Docker.

https://github.com/meteor/meteor/issues/7852#issuecomment-284925574

```
Calling rename(2) for a directory is not fully supported on AUFS.  It returns EXDEV 
(“cross-device link not permitted”),  even when both of the source and the destination path
are on a same AUFS layer, unless the directory  has no children.  So your application has to 
be designed so that it can handle  EXDEV and fall back to a “copy and unlink” strategy.

That said, the fs-extra npm package has the fs.move method which implements error handling 
for that EXDEV error. It has moveDirAcrossDevice and moveFileAcrossDevice methods that 
presumably fix it.
```

**Comment by TannerReynolds** [comment]
Issue fixed next update
